begin;

-- Public visitors apply to one approved partner hospital. Pending/rejected
-- applications stay outside Patients; an accepted application is promoted to
-- users + user_details + Patients in one database transaction.

alter table public."Hospitals"
  add column if not exists "Patient_Applications_Open" boolean not null default false,
  add column if not exists "Patient_Application_Conditions" text,
  add column if not exists "Patient_Application_Requirements" jsonb not null default '[]'::jsonb,
  add column if not exists "Patient_Application_PDF_Path" text,
  add column if not exists "Patient_Application_Settings_Updated_At" timestamp with time zone,
  add column if not exists "Patient_Application_Settings_Updated_By" integer references public.users(user_id) on delete set null;

alter table public."Hospitals"
  drop constraint if exists hospitals_patient_application_requirements_array_check;
alter table public."Hospitals"
  add constraint hospitals_patient_application_requirements_array_check
  check (jsonb_typeof("Patient_Application_Requirements") = 'array');

create table if not exists public."Patient_Applications" (
  "Patient_Application_ID" bigint generated by default as identity primary key,
  "Application_Code" varchar(24) not null unique,
  "Hospital_ID" integer not null references public."Hospitals"("Hospital_ID") on delete restrict,
  "Applicant_Email" varchar(255) not null,
  "Email_Verified_At" timestamp with time zone not null,
  "Status" varchar(40) not null default 'submitted',
  "Submitted_At" timestamp with time zone not null default now(),
  "Reviewed_At" timestamp with time zone,
  "Reviewed_By" integer references public.users(user_id) on delete set null,
  "Decision_Reason" text,
  "Created_Patient_ID" integer references public."Patients"("Patient_ID") on delete set null,

  "First_Name" varchar(255) not null,
  "Middle_Name" varchar(255),
  "Last_Name" varchar(255) not null,
  "Suffix" varchar(50),
  "Birthdate" date not null,
  "Gender" varchar(20) not null,
  "Contact_Number" varchar(50) not null,
  "Street" varchar(255),
  "Barangay" varchar(255),
  "City" varchar(255),
  "Province" varchar(255),
  "Region" varchar(255),
  "Country" varchar(255) not null default 'Philippines',

  "Date_of_Diagnosis" date,
  "Condition_Category" text not null,
  "Medical_Condition" varchar(255) not null,
  "Condition_Stage_Severity" text,
  "Doctor_Name" text,
  "Attending_Physician_Contact" text,
  "Treatment_Hospital_Clinic" text,
  "Treatment_Plan" text,
  "Current_Treatment_Status" text,
  "Allergies_Current_Medications" text,
  "Insurance_PhilHealth_Info" text,
  "Clinical_Special_Note" text,

  "Guardian" varchar(255) not null,
  "Guardian_Relationship" varchar(100) not null,
  "Guardian_Contact_Number" varchar(50) not null,
  "Secondary_Guardian" text,
  "Secondary_Guardian_Relationship" text,
  "Secondary_Guardian_Contact_Number" text,

  "Has_Known_Allergies" boolean,
  "Allergy_Details" text,
  "Has_Sensitive_Scalp" boolean,
  "Has_Scalp_Irritation" boolean,
  "Has_Open_Scalp_Wounds" boolean,
  "Has_Medical_Restriction" boolean,
  "Medical_Restriction_Details" text,
  "Safety_Information_Confirmed" boolean not null default false,

  "Patient_Picture_Path" text,
  "Medical_Document_Path" text not null,
  "Donivra_Terms_Document_ID" integer not null references public.legal_documents(legal_document_id) on delete restrict,
  "Donivra_Terms_Version" text not null,
  "Donivra_Terms_Accepted_At" timestamp with time zone not null,
  "Hospital_Conditions_Accepted_At" timestamp with time zone not null,
  "Hospital_Conditions_Snapshot" jsonb not null,
  "Created_At" timestamp with time zone not null default now(),
  "Updated_At" timestamp with time zone not null default now(),

  constraint patient_applications_email_lowercase_check
    check ("Applicant_Email" = lower(trim("Applicant_Email"))),
  constraint patient_applications_email_format_check
    check ("Applicant_Email" ~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'),
  constraint patient_applications_status_check
    check (public.normalize_flow_key("Status") in ('submitted','accepted','rejected')),
  constraint patient_applications_gender_check
    check (lower("Gender") in ('male','female')),
  constraint patient_applications_condition_check
    check ("Condition_Category" in ('Cancer','Alopecia','Other Hair-Loss Disease')),
  constraint patient_applications_allergy_details_check
    check ("Has_Known_Allergies" is distinct from true or nullif(trim(coalesce("Allergy_Details",'')), '') is not null),
  constraint patient_applications_restriction_details_check
    check ("Has_Medical_Restriction" is distinct from true or nullif(trim(coalesce("Medical_Restriction_Details",'')), '') is not null)
);

create unique index if not exists patient_applications_one_email_idx
  on public."Patient_Applications" (lower("Applicant_Email"));
create index if not exists patient_applications_hospital_status_submitted_idx
  on public."Patient_Applications" ("Hospital_ID", "Status", "Submitted_At" desc);

-- No authenticated or anonymous client writes verification secrets directly.
create table if not exists public.patient_application_email_verifications (
  email text primary key,
  otp_hash text not null,
  otp_salt text not null,
  expires_at timestamp with time zone not null,
  last_sent_at timestamp with time zone not null default now(),
  failed_attempts integer not null default 0,
  verified_at timestamp with time zone,
  submission_token_hash text,
  submission_token_salt text,
  token_expires_at timestamp with time zone,
  consumed_at timestamp with time zone
);

alter table public."Patient_Applications" enable row level security;
alter table public.patient_application_email_verifications enable row level security;

revoke all on table public."Patient_Applications" from public, anon, authenticated;
grant select on table public."Patient_Applications" to authenticated;
revoke all on table public.patient_application_email_verifications from public, anon, authenticated;

-- The Edge Function is the only public-application writer. Grant its service
-- role explicitly instead of depending on project-wide default privileges.
grant select, insert, update on table public."Patient_Applications" to service_role;
grant all on table public.patient_application_email_verifications to service_role;

do $grant_identity$
declare
  v_sequence text := pg_get_serial_sequence(
    'public."Patient_Applications"',
    'Patient_Application_ID'
  );
begin
  if v_sequence is not null then
    execute format('grant usage, select on sequence %s to service_role', v_sequence);
  end if;
end;
$grant_identity$;

drop policy if exists patient_applications_select_hospital_reviewers on public."Patient_Applications";
create policy patient_applications_select_hospital_reviewers
on public."Patient_Applications" for select to authenticated
using (
  exists (
    select 1
    from public.users actor
    where actor.auth_user_id = auth.uid()
      and actor.is_active is distinct from false
      and public.normalize_app_role(actor.role) = 'hrepresentative'
      and exists (
        select 1
        from public."Hospital_Representative" representative
        where representative."User_ID" = actor.user_id
          and (
            (
              public.normalize_flow_key("Patient_Applications"."Status") <> 'accepted'
              and representative."Hospital_ID" = "Patient_Applications"."Hospital_ID"
            )
            or exists (
              select 1 from public."Patients" patient
              where patient."Patient_ID" = "Patient_Applications"."Created_Patient_ID"
                and patient."Hospital_ID" = representative."Hospital_ID"
            )
          )
      )
  )
);

insert into storage.buckets (id, name, public)
values ('patient-application-assets', 'patient-application-assets', false)
on conflict (id) do update set public = false;

insert into storage.buckets (id, name, public)
values ('hospital-application-documents', 'hospital-application-documents', true)
on conflict (id) do update set public = true;

create or replace function public.can_read_patient_application_asset(p_object_name text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $fn$
  select exists (
    select 1
    from public.users actor
    join public."Hospital_Representative" representative
      on representative."User_ID" = actor.user_id
    join public."Patient_Applications" application
      on application."Patient_Picture_Path" = p_object_name
      or application."Medical_Document_Path" = p_object_name
    left join public."Patients" patient
      on patient."Patient_ID" = application."Created_Patient_ID"
    where actor.auth_user_id = auth.uid()
      and actor.is_active is distinct from false
      and public.normalize_app_role(actor.role) = 'hrepresentative'
      and (
        (
          public.normalize_flow_key(application."Status") <> 'accepted'
          and representative."Hospital_ID" = application."Hospital_ID"
        )
        or representative."Hospital_ID" = patient."Hospital_ID"
      )
  );
$fn$;

revoke all on function public.can_read_patient_application_asset(text) from public, anon;
grant execute on function public.can_read_patient_application_asset(text) to authenticated;

drop policy if exists patient_application_assets_select_hospital_reviewers on storage.objects;
create policy patient_application_assets_select_hospital_reviewers
on storage.objects for select to authenticated
using (
  bucket_id = 'patient-application-assets'
  and public.can_read_patient_application_asset(storage.objects.name)
);

-- The global patient-application PDF must be readable before sign-in, but no
-- other legal document in the private bucket is exposed anonymously.
drop policy if exists legal_documents_patient_application_terms_public on storage.objects;
create policy legal_documents_patient_application_terms_public
on storage.objects for select to anon
using (
  bucket_id = 'legal-documents'
  and exists (
    select 1
    from public.legal_documents document
    where document.file_path = storage.objects.name
      and document.document_type = 'patient_application_terms'
      and document.is_active is true
      and document.effective_at <= timezone('Asia/Manila', now())
  )
);

drop policy if exists legal_documents_bucket_insert_admin on storage.objects;
create policy legal_documents_bucket_insert_admin
on storage.objects for insert to authenticated
with check (
  bucket_id = 'legal-documents'
  and (storage.foldername(storage.objects.name))[1] = auth.uid()::text
  and (storage.foldername(storage.objects.name))[2] = 'legal-documents'
  and lower(storage.extension(storage.objects.name)) = 'pdf'
  and exists (
    select 1 from public.users actor
    where actor.auth_user_id = auth.uid()
      and actor.is_active is distinct from false
      and public.normalize_app_role(actor.role) in ('admin','superadmin')
  )
);

drop policy if exists legal_documents_bucket_update_admin on storage.objects;
create policy legal_documents_bucket_update_admin
on storage.objects for update to authenticated
using (
  bucket_id = 'legal-documents'
  and (storage.foldername(storage.objects.name))[1] = auth.uid()::text
  and (storage.foldername(storage.objects.name))[2] = 'legal-documents'
  and exists (
    select 1 from public.users actor
    where actor.auth_user_id = auth.uid()
      and actor.is_active is distinct from false
      and public.normalize_app_role(actor.role) in ('admin','superadmin')
  )
)
with check (
  bucket_id = 'legal-documents'
  and (storage.foldername(storage.objects.name))[1] = auth.uid()::text
  and (storage.foldername(storage.objects.name))[2] = 'legal-documents'
  and lower(storage.extension(storage.objects.name)) = 'pdf'
);

drop policy if exists legal_documents_bucket_delete_admin on storage.objects;
create policy legal_documents_bucket_delete_admin
on storage.objects for delete to authenticated
using (
  bucket_id = 'legal-documents'
  and (storage.foldername(storage.objects.name))[1] = auth.uid()::text
  and (storage.foldername(storage.objects.name))[2] = 'legal-documents'
  and exists (
    select 1 from public.users actor
    where actor.auth_user_id = auth.uid()
      and actor.is_active is distinct from false
      and public.normalize_app_role(actor.role) in ('admin','superadmin')
  )
);

drop policy if exists hospital_application_documents_select_public on storage.objects;
create policy hospital_application_documents_select_public
on storage.objects for select to anon, authenticated
using (bucket_id = 'hospital-application-documents');

drop policy if exists hospital_application_documents_insert_representative on storage.objects;
create policy hospital_application_documents_insert_representative
on storage.objects for insert to authenticated
with check (
  bucket_id = 'hospital-application-documents'
  and exists (
    select 1
    from public.users actor
    where actor.auth_user_id = auth.uid()
      and actor.is_active is distinct from false
      and (
        public.normalize_app_role(actor.role) in ('admin','superadmin')
        or exists (
          select 1 from public."Hospital_Representative" representative
          where representative."User_ID" = actor.user_id
            and representative."Hospital_ID"::text = (storage.foldername(storage.objects.name))[1]
        )
      )
  )
);

drop policy if exists hospital_application_documents_update_representative on storage.objects;
create policy hospital_application_documents_update_representative
on storage.objects for update to authenticated
using (
  bucket_id = 'hospital-application-documents'
  and exists (
    select 1
    from public.users actor
    where actor.auth_user_id = auth.uid()
      and actor.is_active is distinct from false
      and (
        public.normalize_app_role(actor.role) in ('admin','superadmin')
        or exists (
          select 1 from public."Hospital_Representative" representative
          where representative."User_ID" = actor.user_id
            and representative."Hospital_ID"::text = (storage.foldername(storage.objects.name))[1]
        )
      )
  )
)
with check (bucket_id = 'hospital-application-documents');

drop policy if exists hospital_application_documents_delete_representative on storage.objects;
create policy hospital_application_documents_delete_representative
on storage.objects for delete to authenticated
using (
  bucket_id = 'hospital-application-documents'
  and exists (
    select 1
    from public.users actor
    where actor.auth_user_id = auth.uid()
      and actor.is_active is distinct from false
      and (
        public.normalize_app_role(actor.role) in ('admin','superadmin')
        or exists (
          select 1 from public."Hospital_Representative" representative
          where representative."User_ID" = actor.user_id
            and representative."Hospital_ID"::text = (storage.foldername(storage.objects.name))[1]
        )
      )
  )
);

create or replace function public.list_patient_application_hospitals()
returns table (
  hospital_id integer,
  hospital_name text,
  hospital_logo text,
  location text,
  contact_number text,
  applications_open boolean,
  conditions text,
  requirements jsonb,
  requirements_pdf_path text
)
language sql
stable
security definer
set search_path = ''
as $fn$
  select
    hospital."Hospital_ID",
    hospital."Hospital_Name"::text,
    hospital."Hospital_Logo"::text,
    concat_ws(', ', nullif(hospital."City",''), nullif(hospital."Province",''), nullif(hospital."Region",''))::text,
    hospital."Contact_Number"::text,
    hospital."Patient_Applications_Open",
    hospital."Patient_Application_Conditions",
    hospital."Patient_Application_Requirements",
    hospital."Patient_Application_PDF_Path"
  from public."Hospitals" hospital
  where hospital."Is_Approved" is true
    and lower(coalesce(hospital."Approval_Status", '')) = 'approved'
  order by hospital."Patient_Applications_Open" desc, hospital."Hospital_Name";
$fn$;

revoke all on function public.list_patient_application_hospitals() from public;
grant execute on function public.list_patient_application_hospitals() to anon, authenticated;

create or replace function public.get_patient_application_setup(p_hospital_id integer)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $fn$
declare
  v_hospital public."Hospitals"%rowtype;
  v_terms public.legal_documents%rowtype;
begin
  select * into v_hospital
  from public."Hospitals"
  where "Hospital_ID" = p_hospital_id
    and "Is_Approved" is true
    and lower(coalesce("Approval_Status", '')) = 'approved';

  if v_hospital."Hospital_ID" is null then
    raise exception 'Partner hospital was not found';
  end if;

  select * into v_terms
  from public.legal_documents
  where document_type = 'patient_application_terms'
    and is_active is true
    and effective_at <= timezone('Asia/Manila', now())
  order by effective_at desc, created_at desc
  limit 1;

  return jsonb_build_object(
    'hospital', jsonb_build_object(
      'id', v_hospital."Hospital_ID",
      'name', v_hospital."Hospital_Name",
      'logo', v_hospital."Hospital_Logo",
      'location', concat_ws(', ', nullif(v_hospital."Street",''), nullif(v_hospital."Barangay",''), nullif(v_hospital."City",''), nullif(v_hospital."Province",'')),
      'contact_number', v_hospital."Contact_Number",
      'applications_open', v_hospital."Patient_Applications_Open",
      'conditions', v_hospital."Patient_Application_Conditions",
      'requirements', v_hospital."Patient_Application_Requirements",
      'requirements_pdf_path', v_hospital."Patient_Application_PDF_Path",
      'settings_updated_at', v_hospital."Patient_Application_Settings_Updated_At"
    ),
    'donivra_terms', case when v_terms.legal_document_id is null then null else jsonb_build_object(
      'id', v_terms.legal_document_id,
      'title', v_terms.title,
      'version', v_terms.version,
      'content', v_terms.content,
      'file_path', v_terms.file_path,
      'effective_at', v_terms.effective_at
    ) end
  );
end;
$fn$;

revoke all on function public.get_patient_application_setup(integer) from public;
grant execute on function public.get_patient_application_setup(integer) to anon, authenticated;

create or replace function public.get_my_hospital_patient_application_settings()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $fn$
declare
  v_actor public.users%rowtype;
  v_hospital public."Hospitals"%rowtype;
begin
  select * into v_actor from public.users
  where auth_user_id = auth.uid() and is_active is distinct from false limit 1;
  if v_actor.user_id is null or public.normalize_app_role(v_actor.role) <> 'hrepresentative' then
    raise exception 'Only an active H-Representative can view hospital application settings';
  end if;

  select hospital.* into v_hospital
  from public."Hospitals" hospital
  join public."Hospital_Representative" representative
    on representative."Hospital_ID" = hospital."Hospital_ID"
  where representative."User_ID" = v_actor.user_id
  limit 1;

  if v_hospital."Hospital_ID" is null then raise exception 'Hospital assignment was not found'; end if;
  return jsonb_build_object(
    'hospital_id', v_hospital."Hospital_ID",
    'hospital_name', v_hospital."Hospital_Name",
    'applications_open', v_hospital."Patient_Applications_Open",
    'conditions', v_hospital."Patient_Application_Conditions",
    'requirements', v_hospital."Patient_Application_Requirements",
    'requirements_pdf_path', v_hospital."Patient_Application_PDF_Path",
    'updated_at', v_hospital."Patient_Application_Settings_Updated_At"
  );
end;
$fn$;

create or replace function public.update_my_hospital_patient_application_settings(
  p_applications_open boolean,
  p_conditions text,
  p_requirements jsonb,
  p_requirements_pdf_path text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $fn$
declare
  v_actor public.users%rowtype;
  v_hospital_id integer;
begin
  select * into v_actor from public.users
  where auth_user_id = auth.uid() and is_active is distinct from false limit 1;
  if v_actor.user_id is null or public.normalize_app_role(v_actor.role) <> 'hrepresentative' then
    raise exception 'Only an active H-Representative can update hospital application settings';
  end if;

  select representative."Hospital_ID" into v_hospital_id
  from public."Hospital_Representative" representative
  where representative."User_ID" = v_actor.user_id
  limit 1;
  if v_hospital_id is null then raise exception 'Hospital assignment was not found'; end if;
  if jsonb_typeof(coalesce(p_requirements, '[]'::jsonb)) <> 'array' then
    raise exception 'Requirements must be a list';
  end if;
  if exists (
    select 1
    from jsonb_array_elements(coalesce(p_requirements, '[]'::jsonb)) requirement
    where jsonb_typeof(requirement) <> 'string'
      or nullif(trim(requirement #>> '{}'), '') is null
      or length(requirement #>> '{}') > 500
  ) then raise exception 'Every requirement must be non-empty text of 500 characters or less'; end if;
  if jsonb_array_length(coalesce(p_requirements, '[]'::jsonb)) > 30 then
    raise exception 'A hospital can publish at most 30 application requirements';
  end if;
  if nullif(trim(coalesce(p_requirements_pdf_path,'')), '') is not null
    and split_part(trim(p_requirements_pdf_path), '/', 1) <> v_hospital_id::text
  then raise exception 'The requirements PDF must belong to your assigned hospital'; end if;
  if p_applications_open is true
    and nullif(trim(coalesce(p_conditions,'')), '') is null
  then raise exception 'Add the hospital conditions before opening applications'; end if;
  if p_applications_open is true
    and jsonb_array_length(coalesce(p_requirements, '[]'::jsonb)) = 0
  then raise exception 'Add at least one hospital requirement before opening applications'; end if;
  if p_applications_open is true
    and nullif(trim(coalesce(p_requirements_pdf_path,'')), '') is null
  then raise exception 'Upload the hospital requirements PDF before opening applications'; end if;
  if p_applications_open is true and not exists (
    select 1 from public.legal_documents document
    where document.document_type = 'patient_application_terms'
      and document.is_active is true
      and document.effective_at <= timezone('Asia/Manila', now())
  ) then raise exception 'Admin must publish the Donivra patient application terms before applications can open'; end if;

  update public."Hospitals" set
    "Patient_Applications_Open" = coalesce(p_applications_open, false),
    "Patient_Application_Conditions" = nullif(trim(coalesce(p_conditions,'')), ''),
    "Patient_Application_Requirements" = coalesce(p_requirements, '[]'::jsonb),
    "Patient_Application_PDF_Path" = nullif(trim(coalesce(p_requirements_pdf_path,'')), ''),
    "Patient_Application_Settings_Updated_At" = now(),
    "Patient_Application_Settings_Updated_By" = v_actor.user_id,
    "Updated_At" = timezone('Asia/Manila', now())
  where "Hospital_ID" = v_hospital_id;

  insert into public.audit_logs (user_id, action, description, user_email, resource, status, "time")
  values (
    v_actor.user_id, 'patient_applications.settings_updated',
    format('Updated patient application conditions for hospital_id=%s.', v_hospital_id),
    v_actor.email, 'Hospitals:' || v_hospital_id::text, 'success', timezone('Asia/Manila', now())
  );

  return public.get_my_hospital_patient_application_settings();
end;
$fn$;

revoke all on function public.get_my_hospital_patient_application_settings() from public, anon;
revoke all on function public.update_my_hospital_patient_application_settings(boolean,text,jsonb,text) from public, anon;
grant execute on function public.get_my_hospital_patient_application_settings() to authenticated;
grant execute on function public.update_my_hospital_patient_application_settings(boolean,text,jsonb,text) to authenticated;

-- Called only by the patient-application Edge Function after it has verified
-- the signed-in H-Representative and created the Supabase Auth invite.
create or replace function public.finalize_patient_application_acceptance(
  p_application_id bigint,
  p_auth_user_id uuid,
  p_actor_user_id integer,
  p_patient_code text,
  p_patient_picture_path text,
  p_account_setup_url text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $fn$
declare
  v_application public."Patient_Applications"%rowtype;
  v_actor public.users%rowtype;
  v_user_id integer;
  v_patient_id integer;
  v_hospital_name text;
begin
  if nullif(trim(coalesce(p_account_setup_url, '')), '') is null then
    raise exception 'A secure account setup link is required';
  end if;

  select * into v_actor from public.users
  where user_id = p_actor_user_id and is_active is distinct from false;
  if v_actor.user_id is null or public.normalize_app_role(v_actor.role) <> 'hrepresentative' then
    raise exception 'Only an active H-Representative can accept this application';
  end if;

  select * into v_application from public."Patient_Applications"
  where "Patient_Application_ID" = p_application_id for update;
  if v_application."Patient_Application_ID" is null then raise exception 'Application was not found'; end if;
  if public.normalize_flow_key(v_application."Status") <> 'submitted' then
    raise exception 'This application has already been decided';
  end if;
  if not exists (
    select 1 from public."Hospital_Representative" representative
    where representative."User_ID" = v_actor.user_id
      and representative."Hospital_ID" = v_application."Hospital_ID"
  ) then raise exception 'This application belongs to another hospital'; end if;
  if exists (select 1 from public.users where lower(email) = v_application."Applicant_Email") then
    raise exception 'This email already belongs to an existing account';
  end if;

  insert into public.users (auth_user_id, email, role, is_active, created_at, updated_at)
  values (p_auth_user_id, v_application."Applicant_Email", 'patient', true,
    timezone('Asia/Manila', now()), timezone('Asia/Manila', now()))
  returning user_id into v_user_id;

  insert into public.user_details (
    user_id, first_name, middle_name, last_name, suffix, birthdate, gender,
    contact_number, street, barangay, city, province, region, country,
    photo_path, joined_date, created_at, updated_at
  ) values (
    v_user_id, v_application."First_Name", v_application."Middle_Name",
    v_application."Last_Name", v_application."Suffix", v_application."Birthdate",
    v_application."Gender", v_application."Contact_Number", v_application."Street",
    v_application."Barangay", v_application."City", v_application."Province",
    v_application."Region", v_application."Country", p_patient_picture_path,
    current_date, timezone('Asia/Manila', now()), timezone('Asia/Manila', now())
  );

  insert into public."Patients" (
    "User_ID", "Hospital_ID", "Patient_Code", "Medical_Condition",
    "Patient_Picture", "Date_of_Diagnosis", "Guardian",
    "Guardian_Contact_Number", "Medical_Document", "Guardian_Relationship",
    "Medical_Document_Verification_Status", "Medical_Document_Verified_At",
    "Doctor_Name", "Condition_Category",
    "Other_Hair_Loss_Disease", "Condition_Stage_Severity",
    "Attending_Physician_Contact", "Treatment_Hospital_Clinic", "Treatment_Plan",
    "Current_Treatment_Status", "Allergies_Current_Medications",
    "Insurance_PhilHealth_Info", "Clinical_Special_Note", "Secondary_Guardian",
    "Secondary_Guardian_Relationship", "Secondary_Guardian_Contact_Number",
    "Created_By", "Created_At", "Updated_At"
  ) values (
    v_user_id, v_application."Hospital_ID", trim(p_patient_code),
    v_application."Medical_Condition", p_patient_picture_path,
    v_application."Date_of_Diagnosis", v_application."Guardian",
    v_application."Guardian_Contact_Number", v_application."Medical_Document_Path",
    v_application."Guardian_Relationship", 'verified', now(), v_application."Doctor_Name",
    v_application."Condition_Category",
    case when v_application."Condition_Category" = 'Other Hair-Loss Disease'
      then v_application."Medical_Condition" else null end,
    v_application."Condition_Stage_Severity", v_application."Attending_Physician_Contact",
    v_application."Treatment_Hospital_Clinic", v_application."Treatment_Plan",
    v_application."Current_Treatment_Status", v_application."Allergies_Current_Medications",
    v_application."Insurance_PhilHealth_Info", v_application."Clinical_Special_Note",
    v_application."Secondary_Guardian", v_application."Secondary_Guardian_Relationship",
    v_application."Secondary_Guardian_Contact_Number", v_actor.user_id,
    timezone('Asia/Manila', now()), timezone('Asia/Manila', now())
  ) returning "Patient_ID" into v_patient_id;

  insert into public.patient_wig_safety_profiles (
    patient_id, has_known_allergies, allergy_details, has_sensitive_scalp,
    has_scalp_irritation, has_open_scalp_wounds, has_medical_restriction,
    medical_restriction_details, information_confirmed, confirmed_at
  ) values (
    v_patient_id, v_application."Has_Known_Allergies", v_application."Allergy_Details",
    v_application."Has_Sensitive_Scalp", v_application."Has_Scalp_Irritation",
    v_application."Has_Open_Scalp_Wounds", v_application."Has_Medical_Restriction",
    v_application."Medical_Restriction_Details", v_application."Safety_Information_Confirmed", now()
  );

  update public."Patient_Applications" set
    "Status" = 'accepted', "Reviewed_At" = now(), "Reviewed_By" = v_actor.user_id,
    "Decision_Reason" = null, "Created_Patient_ID" = v_patient_id,
    "Patient_Picture_Path" = p_patient_picture_path, "Updated_At" = now()
  where "Patient_Application_ID" = v_application."Patient_Application_ID";

  select "Hospital_Name" into v_hospital_name
  from public."Hospitals"
  where "Hospital_ID" = v_application."Hospital_ID";

  perform public.enqueue_smtp_email_outbox(
    'patient-application-accepted:' || v_application."Patient_Application_ID"::text,
    'Patient_Applications', v_application."Patient_Application_ID"::integer,
    'patient_application_accepted', v_application."Applicant_Email",
    'Your patient application was accepted', 'patient_application_accepted',
    jsonb_build_object(
      'application_code', v_application."Application_Code",
      'applicant_name', concat_ws(' ', v_application."First_Name", v_application."Middle_Name", v_application."Last_Name", v_application."Suffix"),
      'hospital_name', coalesce(v_hospital_name, 'Selected hospital'),
      'patient_code', trim(p_patient_code),
      'account_setup_url', p_account_setup_url
    ),
    v_actor.user_id
  );

  insert into public.audit_logs (user_id, action, description, user_email, resource, status, "time")
  values (
    v_actor.user_id, 'patient_application.accepted',
    format('Accepted patient application %s and created patient %s.', v_application."Application_Code", p_patient_code),
    v_actor.email, 'Patient_Applications:' || v_application."Patient_Application_ID"::text,
    'success', timezone('Asia/Manila', now())
  );

  return jsonb_build_object('application_id', v_application."Patient_Application_ID",
    'patient_id', v_patient_id, 'user_id', v_user_id, 'patient_code', p_patient_code);
end;
$fn$;

revoke all on function public.finalize_patient_application_acceptance(bigint,uuid,integer,text,text,text) from public, anon, authenticated;
grant execute on function public.finalize_patient_application_acceptance(bigint,uuid,integer,text,text,text) to service_role;

create or replace function public.reject_patient_application(
  p_application_id bigint,
  p_actor_user_id integer,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $fn$
declare
  v_application public."Patient_Applications"%rowtype;
  v_actor public.users%rowtype;
  v_hospital_name text;
  v_reason text := nullif(trim(coalesce(p_reason, '')), '');
begin
  if v_reason is null then raise exception 'A rejection reason is required'; end if;

  select * into v_actor from public.users
  where user_id = p_actor_user_id and is_active is distinct from false;
  if v_actor.user_id is null or public.normalize_app_role(v_actor.role) <> 'hrepresentative' then
    raise exception 'Only an active H-Representative can reject this application';
  end if;

  select * into v_application from public."Patient_Applications"
  where "Patient_Application_ID" = p_application_id for update;
  if v_application."Patient_Application_ID" is null then raise exception 'Application was not found'; end if;
  if public.normalize_flow_key(v_application."Status") <> 'submitted' then
    raise exception 'This application has already been decided';
  end if;
  if not exists (
    select 1 from public."Hospital_Representative" representative
    where representative."User_ID" = v_actor.user_id
      and representative."Hospital_ID" = v_application."Hospital_ID"
  ) then raise exception 'This application belongs to another hospital'; end if;

  update public."Patient_Applications" set
    "Status" = 'rejected', "Reviewed_At" = now(), "Reviewed_By" = v_actor.user_id,
    "Decision_Reason" = v_reason, "Updated_At" = now()
  where "Patient_Application_ID" = v_application."Patient_Application_ID";

  select "Hospital_Name" into v_hospital_name
  from public."Hospitals" where "Hospital_ID" = v_application."Hospital_ID";

  perform public.enqueue_smtp_email_outbox(
    'patient-application-rejected:' || v_application."Patient_Application_ID"::text,
    'Patient_Applications', v_application."Patient_Application_ID"::integer,
    'patient_application_rejected', v_application."Applicant_Email",
    'Patient application decision', 'patient_application_rejected',
    jsonb_build_object(
      'application_code', v_application."Application_Code",
      'applicant_name', concat_ws(' ', v_application."First_Name", v_application."Middle_Name", v_application."Last_Name", v_application."Suffix"),
      'hospital_name', coalesce(v_hospital_name, 'Selected hospital'),
      'decision_reason', v_reason
    ),
    v_actor.user_id
  );

  insert into public.audit_logs (user_id, action, description, user_email, resource, status, "time")
  values (
    v_actor.user_id, 'patient_application.rejected',
    format('Rejected patient application %s.', v_application."Application_Code"),
    v_actor.email, 'Patient_Applications:' || v_application."Patient_Application_ID"::text,
    'success', timezone('Asia/Manila', now())
  );

  return jsonb_build_object(
    'application_id', v_application."Patient_Application_ID",
    'application_code', v_application."Application_Code",
    'decision', 'rejected'
  );
end;
$fn$;

revoke all on function public.reject_patient_application(bigint,integer,text) from public, anon, authenticated;
grant execute on function public.reject_patient_application(bigint,integer,text) to service_role;

-- H-Representatives no longer create Patients directly. Patient rows now come
-- only from the reviewed application promotion function; Admin keeps its
-- existing emergency/manual insertion ability.
do $$
declare
  policy_row record;
begin
  for policy_row in
    select policyname from pg_policies
    where schemaname = 'public' and tablename = 'Patients' and cmd = 'INSERT'
  loop
    execute format('drop policy if exists %I on public."Patients"', policy_row.policyname);
  end loop;
end
$$;

create policy patients_insert_admin_only
on public."Patients" for insert to authenticated
with check (
  exists (
    select 1 from public.users actor
    where actor.auth_user_id = auth.uid()
      and actor.is_active is distinct from false
      and public.normalize_app_role(actor.role) in ('admin','superadmin')
  )
);

-- Admin alone publishes the global patient-application terms. Other existing
-- legal-document types keep their current role rules.
create or replace function public.guard_patient_application_global_terms_admin()
returns trigger
language plpgsql
security definer
set search_path = ''
as $fn$
declare
  v_role text;
begin
  if new.document_type <> 'patient_application_terms' then return new; end if;
  select public.normalize_app_role(role) into v_role
  from public.users where auth_user_id = auth.uid() and is_active is distinct from false limit 1;
  if v_role not in ('admin','superadmin') then
    raise exception 'Only Admin can publish Donivra patient application terms';
  end if;
  return new;
end;
$fn$;

drop trigger if exists trg_guard_patient_application_global_terms_admin on public.legal_documents;
create trigger trg_guard_patient_application_global_terms_admin
before insert or update on public.legal_documents
for each row execute function public.guard_patient_application_global_terms_admin();

drop policy if exists legal_documents_patient_application_terms_admin_insert on public.legal_documents;
create policy legal_documents_patient_application_terms_admin_insert
on public.legal_documents for insert to authenticated
with check (
  document_type = 'patient_application_terms'
  and exists (
    select 1 from public.users actor
    where actor.auth_user_id = auth.uid()
      and actor.is_active is distinct from false
      and public.normalize_app_role(actor.role) in ('admin','superadmin')
  )
);

drop policy if exists legal_documents_patient_application_terms_admin_update on public.legal_documents;
create policy legal_documents_patient_application_terms_admin_update
on public.legal_documents for update to authenticated
using (
  document_type = 'patient_application_terms'
  and exists (
    select 1 from public.users actor
    where actor.auth_user_id = auth.uid()
      and actor.is_active is distinct from false
      and public.normalize_app_role(actor.role) in ('admin','superadmin')
  )
)
with check (
  document_type = 'patient_application_terms'
  and exists (
    select 1 from public.users actor
    where actor.auth_user_id = auth.uid()
      and actor.is_active is distinct from false
      and public.normalize_app_role(actor.role) in ('admin','superadmin')
  )
);

do $$
begin
  if to_regclass('public."SMTP_Email_Outbox"') is not null then
    alter table public."SMTP_Email_Outbox"
      drop constraint if exists smtp_email_outbox_notification_type_check;
    alter table public."SMTP_Email_Outbox"
      add constraint smtp_email_outbox_notification_type_check
      check (
        lower(replace(replace(replace(coalesce("Notification_Type", ''), '_', ''), ' ', ''), '-', '')) in (
          'eventapplicationreceived','staffrejected','staffendorsedpendingadmin',
          'adminapproved','adminrejected','partnerhospitalapproved','partnerhospitalrejected',
          'partnerhospitalaccessenabled','partnerhospitalaccessdisabled',
          'eventautocancelled',
          'patientapplicationotp','patientapplicationsubmitted',
          'patientapplicationaccepted','patientapplicationrejected'
        )
      );
  end if;
end
$$;

create or replace function public.enqueue_patient_application_submitted_email()
returns trigger
language plpgsql
security definer
set search_path = ''
as $fn$
declare
  v_hospital_name text;
begin
  if to_regclass('public."SMTP_Email_Outbox"') is null then return new; end if;

  select "Hospital_Name" into v_hospital_name
  from public."Hospitals" where "Hospital_ID" = new."Hospital_ID";

  perform public.enqueue_smtp_email_outbox(
    'patient-application-submitted:' || new."Patient_Application_ID"::text,
    'Patient_Applications', new."Patient_Application_ID"::integer,
    'patient_application_submitted', new."Applicant_Email",
    'Your patient application was received', 'patient_application_submitted',
    jsonb_build_object(
      'application_code', new."Application_Code",
      'hospital_name', coalesce(v_hospital_name, 'Selected hospital'),
      'applicant_name', concat_ws(' ', new."First_Name", new."Middle_Name", new."Last_Name", new."Suffix"),
      'submitted_at', new."Submitted_At",
      'status', 'Pending Hospital Review'
    ),
    null
  );
  return new;
end;
$fn$;

drop trigger if exists trg_enqueue_patient_application_submitted_email
  on public."Patient_Applications";
create trigger trg_enqueue_patient_application_submitted_email
after insert on public."Patient_Applications"
for each row execute function public.enqueue_patient_application_submitted_email();

comment on table public."Patient_Applications" is
  'Public, email-verified applications awaiting a selected partner hospital decision; accepted rows are promoted to Patients.';
comment on column public."Hospitals"."Patient_Application_Conditions" is
  'Hospital-authored patient eligibility conditions shown beside Donivra global terms before application.';

notify pgrst, 'reload schema';
commit;
