begin;

create table if not exists public.wig_release_receipts (
  receipt_id bigint generated by default as identity primary key,
  req_id integer not null unique references public."Wig_Requests"("Req_ID") on delete cascade,
  released_at timestamp without time zone not null,
  appeal_deadline timestamp without time zone not null,
  terms_version text not null default '2026-09-02-v1',
  terms_snapshot text not null,
  received_confirmed_at timestamp without time zone,
  terms_accepted_at timestamp without time zone,
  accepted_by integer references public.users(user_id) on delete set null,
  created_at timestamp without time zone not null default timezone('Asia/Manila', now()),
  updated_at timestamp without time zone not null default timezone('Asia/Manila', now()),
  constraint wig_release_receipts_deadline_check check (appeal_deadline = released_at + interval '7 days'),
  constraint wig_release_receipts_acceptance_check check (
    (terms_accepted_at is null and received_confirmed_at is null and accepted_by is null)
    or (terms_accepted_at is not null and received_confirmed_at is not null and accepted_by is not null)
  )
);

create table if not exists public.wig_release_appeals (
  appeal_id bigint generated by default as identity primary key,
  receipt_id bigint not null references public.wig_release_receipts(receipt_id) on delete cascade,
  req_id integer not null references public."Wig_Requests"("Req_ID") on delete cascade,
  submitted_by integer not null references public.users(user_id) on delete restrict,
  reason text not null,
  description text not null,
  evidence_paths jsonb not null default '[]'::jsonb,
  status text not null default 'Pending Staff Review',
  submitted_at timestamp without time zone not null default timezone('Asia/Manila', now()),
  reviewed_by integer references public.users(user_id) on delete set null,
  reviewed_at timestamp without time zone,
  decision_note text,
  updated_at timestamp without time zone not null default timezone('Asia/Manila', now()),
  constraint wig_release_appeals_one_per_release unique (receipt_id),
  constraint wig_release_appeals_reason_check check (reason in ('Damaged on Receipt', 'Wrong Wig', 'Poor Fit', 'Other')),
  constraint wig_release_appeals_status_check check (status in ('Pending Staff Review', 'Approved for Replacement', 'Rejected')),
  constraint wig_release_appeals_evidence_array_check check (jsonb_typeof(evidence_paths) = 'array'),
  constraint wig_release_appeals_review_check check (
    (status = 'Pending Staff Review' and reviewed_by is null and reviewed_at is null)
    or (status <> 'Pending Staff Review' and reviewed_by is not null and reviewed_at is not null)
  )
);

create index if not exists wig_release_receipts_deadline_idx
  on public.wig_release_receipts(appeal_deadline);
create index if not exists wig_release_appeals_status_submitted_idx
  on public.wig_release_appeals(status, submitted_at desc);
create index if not exists wig_release_appeals_req_idx
  on public.wig_release_appeals(req_id);

create or replace function public.create_wig_release_receipt()
returns trigger
language plpgsql
security definer
set search_path = ''
as $fn$
declare
  v_released_at timestamp without time zone := coalesce(new."Updated_At", timezone('Asia/Manila', now()));
  v_terms text := 'By confirming receipt, the hospital representative acknowledges that the wig was received on behalf of the named patient. The wig must be inspected promptly. Damage, an incorrect wig, or a material fit issue may be appealed within seven calendar days after staff confirms release. Appeals must include an explanation and supporting evidence when available. Requests submitted after the deadline may be declined. Approval of an appeal authorizes replacement review and does not guarantee immediate stock availability.';
begin
  if public.normalize_flow_key(new."Status") = 'released'
    and (tg_op = 'INSERT' or public.normalize_flow_key(old."Status") is distinct from 'released')
  then
    insert into public.wig_release_receipts (
      req_id, released_at, appeal_deadline, terms_version, terms_snapshot, updated_at
    ) values (
      new."Req_ID", v_released_at, v_released_at + interval '7 days', '2026-09-02-v1', v_terms, v_released_at
    )
    on conflict (req_id) do update
      set released_at = excluded.released_at,
          appeal_deadline = excluded.appeal_deadline,
          terms_version = excluded.terms_version,
          terms_snapshot = excluded.terms_snapshot,
          received_confirmed_at = null,
          terms_accepted_at = null,
          accepted_by = null,
          updated_at = excluded.updated_at;
  end if;
  return new;
end;
$fn$;

drop trigger if exists trg_create_wig_release_receipt on public."Wig_Requests";
create trigger trg_create_wig_release_receipt
after insert or update of "Status" on public."Wig_Requests"
for each row execute function public.create_wig_release_receipt();

insert into public.wig_release_receipts (
  req_id, released_at, appeal_deadline, terms_version, terms_snapshot, created_at, updated_at
)
select
  request_row."Req_ID",
  coalesce(request_row."Updated_At", request_row."Request_Date", timezone('Asia/Manila', now())),
  coalesce(request_row."Updated_At", request_row."Request_Date", timezone('Asia/Manila', now())) + interval '7 days',
  '2026-09-02-v1',
  'By confirming receipt, the hospital representative acknowledges that the wig was received on behalf of the named patient. The wig must be inspected promptly. Damage, an incorrect wig, or a material fit issue may be appealed within seven calendar days after staff confirms release. Appeals must include an explanation and supporting evidence when available. Requests submitted after the deadline may be declined. Approval of an appeal authorizes replacement review and does not guarantee immediate stock availability.',
  coalesce(request_row."Updated_At", request_row."Request_Date", timezone('Asia/Manila', now())),
  coalesce(request_row."Updated_At", request_row."Request_Date", timezone('Asia/Manila', now()))
from public."Wig_Requests" request_row
where public.normalize_flow_key(request_row."Status") = 'released'
on conflict (req_id) do nothing;

alter table public.wig_release_receipts enable row level security;
alter table public.wig_release_appeals enable row level security;
grant select on public.wig_release_receipts, public.wig_release_appeals to authenticated;

drop policy if exists wig_release_receipts_select_authorized on public.wig_release_receipts;
create policy wig_release_receipts_select_authorized
on public.wig_release_receipts for select to authenticated
using (
  exists (
    select 1
    from public.users actor
    join public."Wig_Requests" request_row on request_row."Req_ID" = wig_release_receipts.req_id
    where actor.auth_user_id = (select auth.uid())
      and actor.is_active is distinct from false
      and (
        public.normalize_app_role(actor.role) in ('staff', 'admin', 'superadmin')
        or exists (
          select 1 from public."Hospital_Representative" assignment
          where assignment."User_ID" = actor.user_id
            and assignment."Hospital_ID" = request_row."Hospital_ID"
        )
      )
  )
);

drop policy if exists wig_release_appeals_select_authorized on public.wig_release_appeals;
create policy wig_release_appeals_select_authorized
on public.wig_release_appeals for select to authenticated
using (
  exists (
    select 1
    from public.users actor
    join public."Wig_Requests" request_row on request_row."Req_ID" = wig_release_appeals.req_id
    where actor.auth_user_id = (select auth.uid())
      and actor.is_active is distinct from false
      and (
        public.normalize_app_role(actor.role) in ('staff', 'admin', 'superadmin')
        or exists (
          select 1 from public."Hospital_Representative" assignment
          where assignment."User_ID" = actor.user_id
            and assignment."Hospital_ID" = request_row."Hospital_ID"
        )
      )
  )
);

create or replace function public.hrep_confirm_wig_receipt_terms(
  p_req_id integer,
  p_terms_version text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $fn$
declare
  v_actor public.users%rowtype;
  v_request public."Wig_Requests"%rowtype;
  v_receipt public.wig_release_receipts%rowtype;
  v_now timestamp without time zone := timezone('Asia/Manila', now());
begin
  select * into v_actor from public.users where auth_user_id = auth.uid() and is_active is distinct from false limit 1;
  if v_actor.user_id is null then raise exception 'Authentication required'; end if;

  select * into v_request from public."Wig_Requests" where "Req_ID" = p_req_id;
  if v_request."Req_ID" is null then raise exception 'Wig request was not found'; end if;
  if public.normalize_flow_key(v_request."Status") <> 'released' then raise exception 'Only a released wig can be confirmed as received'; end if;
  if not exists (
    select 1 from public."Hospital_Representative" assignment
    where assignment."User_ID" = v_actor.user_id and assignment."Hospital_ID" = v_request."Hospital_ID"
  ) then raise exception 'You are not authorized for this hospital request'; end if;

  select * into v_receipt from public.wig_release_receipts where req_id = p_req_id for update;
  if v_receipt.receipt_id is null then raise exception 'Release receipt record is unavailable'; end if;
  if trim(coalesce(p_terms_version, '')) <> v_receipt.terms_version then raise exception 'The terms changed. Refresh and review the current version'; end if;

  update public.wig_release_receipts
  set received_confirmed_at = coalesce(received_confirmed_at, v_now),
      terms_accepted_at = coalesce(terms_accepted_at, v_now),
      accepted_by = coalesce(accepted_by, v_actor.user_id),
      updated_at = v_now
  where receipt_id = v_receipt.receipt_id
  returning * into v_receipt;

  insert into public.audit_logs (user_id, action, description, user_email, resource, status)
  values (v_actor.user_id, 'wig_release.receipt_terms_accepted', format('request_id=%s terms=%s', p_req_id, v_receipt.terms_version), v_actor.email, 'wig_release_receipts', 'success');

  return to_jsonb(v_receipt);
end;
$fn$;

create or replace function public.hrep_submit_wig_release_appeal(
  p_req_id integer,
  p_reason text,
  p_description text,
  p_evidence_paths jsonb default '[]'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $fn$
declare
  v_actor public.users%rowtype;
  v_request public."Wig_Requests"%rowtype;
  v_receipt public.wig_release_receipts%rowtype;
  v_appeal public.wig_release_appeals%rowtype;
  v_now timestamp without time zone := timezone('Asia/Manila', now());
begin
  select * into v_actor from public.users where auth_user_id = auth.uid() and is_active is distinct from false limit 1;
  if v_actor.user_id is null then raise exception 'Authentication required'; end if;
  select * into v_request from public."Wig_Requests" where "Req_ID" = p_req_id;
  if v_request."Req_ID" is null then raise exception 'Wig request was not found'; end if;
  if not exists (
    select 1 from public."Hospital_Representative" assignment
    where assignment."User_ID" = v_actor.user_id and assignment."Hospital_ID" = v_request."Hospital_ID"
  ) then raise exception 'You are not authorized for this hospital request'; end if;

  select * into v_receipt from public.wig_release_receipts where req_id = p_req_id for update;
  if v_receipt.terms_accepted_at is null then raise exception 'Confirm receipt and accept the terms before submitting an appeal'; end if;
  if v_now > v_receipt.appeal_deadline then raise exception 'The seven-day appeal period has ended'; end if;
  if trim(coalesce(p_reason, '')) not in ('Damaged on Receipt', 'Wrong Wig', 'Poor Fit', 'Other') then raise exception 'Select a valid appeal reason'; end if;
  if length(trim(coalesce(p_description, ''))) < 20 then raise exception 'Describe the issue using at least 20 characters'; end if;
  if jsonb_typeof(coalesce(p_evidence_paths, '[]'::jsonb)) <> 'array' then raise exception 'Evidence must be a list of uploaded files'; end if;

  insert into public.wig_release_appeals (receipt_id, req_id, submitted_by, reason, description, evidence_paths, submitted_at, updated_at)
  values (v_receipt.receipt_id, p_req_id, v_actor.user_id, trim(p_reason), trim(p_description), coalesce(p_evidence_paths, '[]'::jsonb), v_now, v_now)
  returning * into v_appeal;

  insert into public.audit_logs (user_id, action, description, user_email, resource, status)
  values (v_actor.user_id, 'wig_release.appeal_submitted', format('request_id=%s appeal_id=%s', p_req_id, v_appeal.appeal_id), v_actor.email, 'wig_release_appeals', 'success');
  return to_jsonb(v_appeal);
end;
$fn$;

create or replace function public.staff_review_wig_release_appeal(
  p_appeal_id bigint,
  p_decision text,
  p_decision_note text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $fn$
declare
  v_actor public.users%rowtype;
  v_appeal public.wig_release_appeals%rowtype;
  v_request public."Wig_Requests"%rowtype;
  v_recipient integer;
  v_status text;
  v_now timestamp without time zone := timezone('Asia/Manila', now());
begin
  select * into v_actor from public.users where auth_user_id = auth.uid() and is_active is distinct from false limit 1;
  if v_actor.user_id is null or public.normalize_app_role(v_actor.role) not in ('staff', 'admin', 'superadmin') then
    raise exception 'Only active staff or admin accounts can review appeals';
  end if;
  v_status := case lower(trim(coalesce(p_decision, ''))) when 'approve' then 'Approved for Replacement' when 'reject' then 'Rejected' else null end;
  if v_status is null then raise exception 'Decision must be approve or reject'; end if;
  if length(trim(coalesce(p_decision_note, ''))) < 10 then raise exception 'Add a decision note using at least 10 characters'; end if;

  select * into v_appeal from public.wig_release_appeals where appeal_id = p_appeal_id for update;
  if v_appeal.appeal_id is null then raise exception 'Appeal was not found'; end if;
  if v_appeal.status <> 'Pending Staff Review' then raise exception 'This appeal has already been reviewed'; end if;

  update public.wig_release_appeals
  set status = v_status, reviewed_by = v_actor.user_id, reviewed_at = v_now,
      decision_note = trim(p_decision_note), updated_at = v_now
  where appeal_id = p_appeal_id returning * into v_appeal;

  select * into v_request from public."Wig_Requests" where "Req_ID" = v_appeal.req_id;
  for v_recipient in
    select distinct recipient_id from (values (v_request."Requested_By")) recipients(recipient_id) where recipient_id is not null
  loop
    insert into public."Notification" ("User_ID", "Type", "Title", "Message", "Status", "Reference_Type", "Reference_ID", "Updated_At")
    values (v_recipient, 'Wig Appeal', 'Wig appeal reviewed', format('%s appeal: %s.', coalesce(v_request."Request_Code", 'Wig request'), v_status), 'Unread', 'wig_release_appeals', p_appeal_id::text, v_now);
  end loop;

  insert into public.audit_logs (user_id, action, description, user_email, resource, status)
  values (v_actor.user_id, 'wig_release.appeal_reviewed', format('appeal_id=%s decision=%s', p_appeal_id, v_status), v_actor.email, 'wig_release_appeals', 'success');
  return to_jsonb(v_appeal);
end;
$fn$;

revoke all on function public.hrep_confirm_wig_receipt_terms(integer, text) from public, anon;
revoke all on function public.hrep_submit_wig_release_appeal(integer, text, text, jsonb) from public, anon;
revoke all on function public.staff_review_wig_release_appeal(bigint, text, text) from public, anon;
grant execute on function public.hrep_confirm_wig_receipt_terms(integer, text) to authenticated;
grant execute on function public.hrep_submit_wig_release_appeal(integer, text, text, jsonb) to authenticated;
grant execute on function public.staff_review_wig_release_appeal(bigint, text, text) to authenticated;

notify pgrst, 'reload schema';
commit;
